version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "med-challenge-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j448tatkevwe"
s3_prefix = "med-challenge-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
